/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
//import java.sql.*;
//import java.sql.Connection;
//import java.sql.DriverManager;
//import java.sql.ResultSet;
//import java.sql.ResultSetMetaData;
//import java.sql.SQLException;
//import java.sql.Statement;
import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SATRIA
 */
public class TiketKA extends javax.swing.JFrame {
    int hekonomi,hbisnis,heksekutif,harga,beli,totalbayar;
    private Object cmbJurusan;
//private Connection con;
//    private String[][] dataTable;
//    private String[] header = {"ID","Nama","Kode Kereta","Nama Kereta","Jurusan","Jenis Kereta","Harga","Jumlah Beli","Total Bayar"};
    /**
     * Creates new form Home
     */
    public TiketKA() {
        initComponents();
//        koneksiDatabase();
//        simpanData();
//        tampilDataKeTabel();
//        hapusData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnHotel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bbeli = new javax.swing.JButton();
        blagi = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        tnama = new javax.swing.JTextField();
        cmbkode = new javax.swing.JComboBox();
        tkereta = new javax.swing.JTextField();
        cmbjurusan = new javax.swing.JComboBox();
        cmbjenis = new javax.swing.JComboBox();
        tharga = new javax.swing.JTextField();
        tbeli = new javax.swing.JTextField();
        ttotalbayar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tarea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(54, 33, 89));
        bg.setForeground(new java.awt.Color(54, 33, 89));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(54, 33, 89));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TiketinAja");

        jPanel3.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(85, 65, 118));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/plane (1).png"))); // NOI18N
        jButton1.setText("   Tiket Pesawat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnHotel.setBackground(new java.awt.Color(85, 65, 118));
        btnHotel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHotel.setForeground(new java.awt.Color(255, 255, 255));
        btnHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/underground.png"))); // NOI18N
        btnHotel.setText("   Tiket Kereta Api");
        btnHotel.setToolTipText("");
        btnHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHotelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidepaneLayout = new javax.swing.GroupLayout(sidepane);
        sidepane.setLayout(sidepaneLayout);
        sidepaneLayout.setHorizontalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHotel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addGroup(sidepaneLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sidepaneLayout.setVerticalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(549, Short.MAX_VALUE))
        );

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 760));

        jPanel1.setBackground(new java.awt.Color(77, 46, 128));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Masuk atau Daftar untuk melengkapi pemesanan Tiket Pesawat");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/air asia.png"))); // NOI18N

        jLabel22.setBackground(new java.awt.Color(77, 46, 128));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/icon train.png"))); // NOI18N
        jLabel22.setMinimumSize(new java.awt.Dimension(100, 268));
        jLabel22.setOpaque(true);
        jLabel22.setPreferredSize(new java.awt.Dimension(100, 268));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tiket");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kereta Api");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 630, 100));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 33, 89)), "Data Kereta Api", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(54, 33, 89))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(54, 33, 89));
        jLabel1.setText("ID Data");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(54, 33, 89));
        jLabel12.setText("Nama Penumpang");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(54, 33, 89));
        jLabel13.setText("Kode Kereta");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(54, 33, 89));
        jLabel15.setText("Nama Kereta");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(54, 33, 89));
        jLabel16.setText("Jurusan");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(54, 33, 89));
        jLabel17.setText("Harga");

        bbeli.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bbeli.setForeground(new java.awt.Color(54, 33, 89));
        bbeli.setText("Beli");
        bbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbeliActionPerformed(evt);
            }
        });

        blagi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        blagi.setForeground(new java.awt.Color(54, 33, 89));
        blagi.setText("Beli Lagi");
        blagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blagiActionPerformed(evt);
            }
        });

        bhapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bhapus.setForeground(new java.awt.Color(54, 33, 89));
        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        bkeluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bkeluar.setForeground(new java.awt.Color(54, 33, 89));
        bkeluar.setText("Keluar");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(54, 33, 89));
        jLabel18.setText("Jenis Kereta");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(54, 33, 89));
        jLabel19.setText("Jumlah Beli");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(54, 33, 89));
        jLabel5.setText("Total Bayar");

        tid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tid.setForeground(new java.awt.Color(54, 33, 89));

        tnama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tnama.setForeground(new java.awt.Color(54, 33, 89));

        cmbkode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbkode.setForeground(new java.awt.Color(54, 33, 89));
        cmbkode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---- PILIH KODE KERETA ----", "KRL001", "KRL002", "KRL003" }));
        cmbkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkodeActionPerformed(evt);
            }
        });

        tkereta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tkereta.setForeground(new java.awt.Color(54, 33, 89));

        cmbjurusan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbjurusan.setForeground(new java.awt.Color(54, 33, 89));
        cmbjurusan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---- JURUSAN ----", "JAKARTA - CIREBON", "JAKARTA - SOLO", "JAKARTA - BANDUNG", "JAKARTA - YOGYAKARTA", "JAKARTA - SURABAYA", "JAKARTA - PEKALONGAN" }));
        cmbjurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbjurusanActionPerformed(evt);
            }
        });

        cmbjenis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbjenis.setForeground(new java.awt.Color(54, 33, 89));
        cmbjenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---- PILIH JENIS KERETA ----", "EKONOMI", "BISNIS", "EKSEKUTIF" }));
        cmbjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbjenisActionPerformed(evt);
            }
        });

        tharga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        tbeli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbeli.setForeground(new java.awt.Color(54, 33, 89));
        tbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbeliActionPerformed(evt);
            }
        });
        tbeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbeliKeyReleased(evt);
            }
        });

        ttotalbayar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ttotalbayar.setForeground(new java.awt.Color(54, 33, 89));

        tarea.setColumns(20);
        tarea.setRows(5);
        jScrollPane2.setViewportView(tarea);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(bbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(blagi, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(bkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel5)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tid)
                            .addComponent(tnama)
                            .addComponent(cmbkode, 0, 379, Short.MAX_VALUE)
                            .addComponent(tkereta)
                            .addComponent(cmbjurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbjenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tharga)
                            .addComponent(tbeli)
                            .addComponent(ttotalbayar))))
                .addGap(31, 31, 31))
            .addComponent(jScrollPane2)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbkode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tkereta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cmbjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cmbjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tharga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ttotalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blagi)
                    .addComponent(bhapus)
                    .addComponent(bkeluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
        );

        bg.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 610, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(900, 771));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbeliActionPerformed
        // TODO add your handling code here:
        tarea.setText(
                "ID Penumpang        : "+tid.getText()+"\n"+
                "Nama Penumpang      : "+tnama.getText()+"\n"+
                "Nama Kereta         : "+tkereta.getText()+"\n"+
                "Harga               : "+tharga.getText()+"\n"+
                "Jumlah Beli         : "+tbeli.getText()+"\n"+
                "Total Bayar         : "+ttotalbayar.getText()+"\n");
    }//GEN-LAST:event_bbeliActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_bhapusActionPerformed

    private void blagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blagiActionPerformed
        // TODO add your handling code here:
         tid.setText("");
        tnama.setText("");
        cmbkode.setSelectedItem("---- PILIH KODE KERETA ----");
        tkereta.setText("");
        cmbjurusan.setSelectedItem("---- JURUSAN ----");
        cmbjenis.setSelectedItem("---- PILIH JENIS KERETA ----");
        tharga.setText("");
        tbeli.setText("");
        ttotalbayar.setText("");
    }//GEN-LAST:event_blagiActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(null, "Anda Yakin Ingin Keluar", "Selesai", JOptionPane.OK_OPTION);
        if (answer == JOptionPane.OK_OPTION){
            dispose();
        }
    }//GEN-LAST:event_bkeluarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHotelActionPerformed
        // TODO add your handling code here:
        new TiketKA().setVisible(true);
    }//GEN-LAST:event_btnHotelActionPerformed

    private void cmbkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkodeActionPerformed
        // TODO add your handling code here:
    if(cmbkode.getSelectedItem().equals("KRL001")){
        tkereta.setText("ARGOJATI");
        cmbjurusan.addItem("---- JURUSAN ----");
        cmbjurusan.addItem("JAKARTA - CIREBON");
        cmbjurusan.addItem("JAKARTA - SOLO");
    }
    else if(cmbkode.getSelectedItem().equals("KRL002")){
        tkereta.setText("ARGO PARAHYANGAN");
        cmbjurusan.addItem("---- JURUSAN ----");
        cmbjurusan.addItem("JAKARTA - BANDUNG");
        cmbjurusan.addItem("JAKARTA - YOGYAKARTA");
    }
    else if(cmbkode.getSelectedItem().equals("KRL003")){
        tkereta.setText("ARGO BROMO ANGGREK");
        cmbjurusan.addItem("---- JURUSAN ----");
        cmbjurusan.addItem("JAKARTA - SURABAYA");
        cmbjurusan.addItem("JAKARTA - PEKALONGAN");
    }
    else if(cmbkode.getSelectedItem().equals("---- PILIH KODE KERETA ----")){
        tkereta.setText("");
    }
    }//GEN-LAST:event_cmbkodeActionPerformed

    private void cmbjurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbjurusanActionPerformed
        // TODO add your handling code here:
    if(cmbjurusan.getSelectedItem().equals("---- JURUSAN ----")){
        buttonGroup2.clearSelection();
        tharga.setText("");
    }else if(cmbjurusan.getSelectedItem().equals("JAKARTA - CIREBON")){
        hekonomi=75000;
        hbisnis=150000;
        heksekutif=100000;
    }else if(cmbjurusan.getSelectedItem().equals("JAKARTA - SOLO")){
        hekonomi=75000;
        hbisnis=155000;
        heksekutif=200000;
    }
    else if(cmbjurusan.getSelectedItem().equals("JAKARTA - BANDUNG")){
        hekonomi=100000;
        hbisnis=300000;
        heksekutif=250000;
    }
    else if(cmbjurusan.getSelectedItem().equals("JAKARTA - YOGYAKARTA")){
        hekonomi=75000;
        hbisnis=275000;
        heksekutif=300000;
    }
    else if(cmbjurusan.getSelectedItem().equals("JAKARTA - SURABAYA")){
        hekonomi=50000;
        hbisnis=100000;
        heksekutif=150000;
    }
    else if(cmbjurusan.getSelectedItem().equals("JAKARTA - PEKALONGAN")){
        hekonomi=95000;
        hbisnis=170000;
        heksekutif=200000;
    }
    }//GEN-LAST:event_cmbjurusanActionPerformed

    private void cmbjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbjenisActionPerformed
        // TODO add your handling code here:
    if(cmbjenis.getSelectedItem().equals("---- PILIH JENIS KERETA ----")){
        tharga.setText("");
    }
    else if(cmbjenis.getSelectedItem().equals("EKONOMI")){
        tharga.setText(String.valueOf(hekonomi));
    }
    else if(cmbjenis.getSelectedItem().equals("BISNIS")){
        tharga.setText(String.valueOf(hbisnis));
    }
    else if(cmbjenis.getSelectedItem().equals("EKSEKUTIF")){
        tharga.setText(String.valueOf(heksekutif));
    }
    }//GEN-LAST:event_cmbjenisActionPerformed

    private void tbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbeliActionPerformed
        // TODO add your handling code here:
        beli=Integer.parseInt(tbeli.getText());
        harga=Integer.parseInt(tharga.getText());
        totalbayar=beli*harga;
        ttotalbayar.setText(String.valueOf(totalbayar));
    }//GEN-LAST:event_tbeliActionPerformed

    private void tbeliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbeliKeyReleased
        // TODO add your handling code here:
        int a, b, c;
        a=Integer.valueOf(tharga.getText());
        b=Integer.valueOf(tbeli.getText());
        c=a*b;
        ttotalbayar.setText(""+c);
    }//GEN-LAST:event_tbeliKeyReleased

//    public void koneksiDatabase(){
//        try{
//            Class.forName("com.mysql.jdbc.Driver");
//            con = DriverManager.getConnection("jdbc:mysql://localhost/tiketinaja","root","");
//            System.out.println("Koneksi ke MySQL Server berhasil!");
//        }catch(ClassNotFoundException eclass){
//            System.out.println("Driver tidak ada!");
//        }catch(SQLException esql){
//            System.out.println(esql.getMessage());
//        }
//    }
    
//    private void hapusData(){
//        try{
//            String sql = "DELETE FROM keretaapi WHERE id_penumpang = \""+tid.getText()+"\"";
//            Statement stmt = con.createStatement();
//            stmt.executeUpdate(sql);
//            System.out.println("Berhasil dihapus!");
//        }catch(Exception e){
//            System.out.println(e);
//        }
//        tid.setText("");
//        tnama.setText("");
//        cmbkode.setSelectedItem("---- PILIH KODE KERETA ----");
//        tkereta.setText("");
//        cmbjurusan.setSelectedItem("---- JURUSAN ----");
//        cmbjenis.setSelectedItem("---- PILIH JENIS KERETA ----");
//        tharga.setText("");
//        tbeli.setText("");
//        ttotalbayar.setText("");
//        tampilDataKeTabel();
//    }
    
//    public void simpanData(){
//        try {
//            String sql;
//            sql = "Insert into keretaapi set id_penumpang = \"" + tid.getText() + "\","
//                    + "nama = \"" + tnama.getText() + "\","
//                    + "kode = \"" + (String)cmbkode.getSelectedItem() + "\","
//                    + "nm_kereta = \"" + tkereta.getText() + "\","
//                    + "jurusan = \"" + (String)cmbjurusan.getSelectedItem() + "\","
//                    + "jenis = \"" + (String)cmbjenis.getSelectedItem() + "\","
//                    + "harga = \"" + tharga.getText() + "\","
//                    + "jumlah_beli = \"" + tbeli.getText() + "\","
//                    + "total = \"" + ttotalbayar.getText() + "\",";
//            Statement stmt = con.createStatement();
//            stmt.executeUpdate(sql);
//            System.out.println("berhasil!");
//        }catch (Exception e){
//            System.out.println(e);
//        }
//        tampilDataKeTabel();
//    }
    
//    public void tampilDataKeTabel(){
//        ResultSet rs = null;
//        try{
//            Statement stmt = con.createStatement();
//            rs = stmt.executeQuery("select * from keretaapi");
//            
//            ResultSetMetaData meta = rs.getMetaData();
//            int col = meta.getColumnCount();
//            int baris = 0;
//            while (rs.next()){
//                baris = rs.getRow();
//            }
//            dataTable = new String[baris][col];
//            int x = 0;
//            rs.beforeFirst();
//            while(rs.next()){
//                dataTable[x][0] = rs.getString("id_penumpang");
//                dataTable[x][1] = rs.getString("nama");
//                dataTable[x][2] = rs.getString("kode");
//                dataTable[x][3] = rs.getString("nm_kereta");
//                dataTable[x][4] = rs.getString("jurusan");
//                dataTable[x][5] = rs.getString("jenis");
//                dataTable[x][6] = rs.getString("harga");
//                dataTable[x][7] = rs.getString("jumlah_bayar");
//                dataTable[x][8] = rs.getString("total");
//                x++;
//            }
//            DisplayTable.setModel(new DefaultTableModel(dataTable,header));
//        }catch(Exception e){
//            System.err.println("ada yang salah:"+e);
//        }
//    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TiketKA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbeli;
    private javax.swing.JPanel bg;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton blagi;
    private javax.swing.JButton btnHotel;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cmbjenis;
    private javax.swing.JComboBox cmbjurusan;
    private javax.swing.JComboBox cmbkode;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel sidepane;
    private javax.swing.JTextArea tarea;
    private javax.swing.JTextField tbeli;
    private javax.swing.JTextField tharga;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tkereta;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField ttotalbayar;
    // End of variables declaration//GEN-END:variables

    private void If(boolean equals) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
